# Generated by Django 3.2.13 on 2022-04-23 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
