# Generated by Django 3.2.13 on 2022-04-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0003_alter_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
